---
abstract: 'PAR Packager'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PAR-Packer
no_index:
  directory:
    - contrib
    - inc
    - t
recommends:
  Digest: Module::Signature
requires:
  Archive::Zip: 1
  Compress::Zlib: 1.3
  File::Temp: 0.05
  Getopt::ArgvFile: 1.07
  Module::ScanDeps: 0.78
  PAR: 0.977
  PAR::Dist: 0.22
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.991
