--- 
abstract: PAR Packager
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PAR-Packer
no_index: 
  directory: 
    - contrib
    - inc
    - t
provides: 
  App::Packer::PAR: 
    file: lib/App/Packer/PAR.pm
    version: 0.91
  PAR::Filter: 
    file: lib/PAR/Filter.pm
    version: 0.02
  PAR::Filter::Bleach: 
    file: lib/PAR/Filter/Bleach.pm
  PAR::Filter::Bytecode: 
    file: lib/PAR/Filter/Bytecode.pm
  PAR::Filter::Obfuscate: 
    file: lib/PAR/Filter/Obfuscate.pm
  PAR::Filter::PatchContent: 
    file: lib/PAR/Filter/PatchContent.pm
  PAR::Filter::PodStrip: 
    file: lib/PAR/Filter/PodStrip.pm
  PAR::Packer: 
    file: lib/PAR/Packer.pm
    version: 0.973
  PAR::StrippedPARL::Base: 
    file: lib/PAR/StrippedPARL/Base.pm
    version: 0.958
  PAR::StrippedPARL::Dynamic: 
    file: lib/PAR/StrippedPARL/Dynamic.pm
    version: 0.958
  PAR::StrippedPARL::Static: 
    file: lib/PAR/StrippedPARL/Static.pm
    version: 0.958
  pp: 
    file: lib/pp.pm
    version: ''
recommends: 
  Digest: Module::Signature
requires: 
  Archive::Zip: 1
  Compress::Zlib: 1.3
  File::Temp: 0.05
  Getopt::ArgvFile: 1.07
  Module::ScanDeps: 0.7
  PAR: 0.971
  PAR::Dist: 0.21
  perl: 5.6.0
version: 0.973
